# THIS FILE IS OUT OF BOUNDS

language: python
python:
  - "3.6"
script:
  - ./validate-on-master.sh
branches:
  only:
    - master
git:
  depth: false
notifications:
  email:
    recipients:
      - jeff@jefftk.com
    on_success: never
    on_failure: always
